import type { Metadata } from "next";
import { Wix_Madefor_Text } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./Theme-Provider";
import { switchThemeDuration } from "./constants";
import Fabicon from "./components/Fabicon";
import Navbar from "./components/Navbar";
import NextTopLoader from "nextjs-toploader";
import Footer from "./components/Footer";

const inter = Wix_Madefor_Text({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Tejas K Saindane | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-slate-50 dark:bg-[#050816] ${switchThemeDuration}`}
      >
        <NextTopLoader
          color="#915EFF"
          initialPosition={0.08}
          crawlSpeed={500}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={500}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="h-16 w-full top-0 left-0 fixed z-1000 opacity-100">
            <Navbar />
          </div>

          <Fabicon />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
